use_frameworks!

platform :ios, '9.0'

target 'LBCAnnouncementsCore_Example' do
  pod 'LBCAnnouncementsCore', :path => '../'

  target 'LBCAnnouncementsCore_Tests' do
    inherit! :search_paths

    
  end
end
